apiVersion: v1
kind: Service
metadata:
  name: {{ include "danswer-stack.fullname" . }}-indexing-model-service
  labels:
    {{- include "danswer-stack.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "danswer-stack.selectorLabels" . | nindent 4 }}
    {{- if .Values.indexCapability.deploymentLabels }}
    {{- toYaml .Values.indexCapability.deploymentLabels | nindent 4 }}
    {{- end }}
  ports:
    - name: {{ .Values.indexCapability.service.name }}
      protocol: TCP
      port: {{ .Values.indexCapability.service.port }}
      targetPort: {{ .Values.indexCapability.service.port }}
  type: {{ .Values.indexCapability.service.type }}