name: Quality Checks PR
concurrency:
  group: Quality-Checks-PR-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request: null

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
